language: python
before_install:
  - sudo add-apt-repository ppa:chris-lea/pylint -y
  - sudo apt-get -qq update
  - sudo apt-get install -y pylint3
python:
  - "3.6"
install:
  - pip3 install pylint cassandra-driver Flask
cache:
  - pip
script:
  - for i in $(find . -name *.py); do echo $i; pylint3 -d C0103 $i; done
