language: python
python:
  - "3.6"
install:
  - pip3 install python-digitalocean
cache:
  - pip
env:
  - IMAGE_NAME=testhost-11.03.2018-16.02
script:
  - python3 CI/run_instance.py
  - python3 CI/execute_tests.py
  - python3 CI/terminate_instance.py
